name       : opentoonz
version    : 1.3.0
release    : 5
homepage   : https://opentoonz.github.io/
source     :
    - https://github.com/opentoonz/opentoonz/archive/v1.3.0.tar.gz : a5dd0286a58017a086a3533016b9b4f54ada25a230c62de63b995bc04d0cd5a8
license    :
    - BSD-3-Clause
    - CC0-1.0
component  : multimedia.video
summary    : An open-source full-featured 2D animation creation software
description: |
    OpenToonz is a 2D animation software published by DWANGO. It is based on Toonz Studio Ghibli Version, originally developed in Italy by Digital Video, Inc., and customized by Studio Ghibli over many years of production.
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libmypaint)
    - pkgconfig(libusb)
    - pkgconfig(openblas)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sdl2)
    - libboost-devel
    - lzo-devel
    - superlu-devel
clang      : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-Qt-5.13-build-error-2665.patch
    # currently opentoonz needs its own modified version of libtiff
    pushd thirdparty/tiff-4.0.3
      %configure --with-pic --disable-jbig
      %make
    popd

    %cmake -S toonz/sources
build      : |
    %make
install    : |
    %make_install
